

class MockData {

  static final exampleList = [

    <String, dynamic> {
      "image": "Alpine_Landscape_(250461587).jpeg",
      "title": "Alpine Landscape",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the Alpine Landscape image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. \n\n A valley is an elongated low area often running between hills or mountains, which will typically contain a river or stream running from one end to the other. Most valleys are formed by erosion of the land surface by rivers or streams over a very long period. Some valleys are formed through erosion by glacial ice. These glaciers may remain present in valleys in high mountains or polar areas. \n\n At lower latitudes and altitudes, these glacially formed valleys may have been created or enlarged during ice ages but now are ice-free and occupied by streams or rivers. In desert areas, valleys may be entirely dry or carry a watercourse only rarely. In areas of limestone bedrock, dry valleys may also result from drainage now taking place underground rather than at the surface. Rift valleys arise principally from earth movements, rather than erosion. Many different types of valleys are described by geographers, using terms that may be global in use or else applied only locally. ",
      "licenceUrl": "https://commons.wikimedia.org/wiki/File:Alpine_Landscape_%28250461587%29.jpeg#metadata"
    },
    <String, dynamic> {
      "image": "An_Alpine_Landscape_NZ.jpg",
      "title": "An Alpine Landscape",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the An Alpine Landscape image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. \n\n A valley is an elongated low area often running between hills or mountains, which will typically contain a river or stream running from one end to the other. Most valleys are formed by erosion of the land surface by rivers or streams over a very long period. Some valleys are formed through erosion by glacial ice. These glaciers may remain present in valleys in high mountains or polar areas. \n\n At lower latitudes and altitudes, these glacially formed valleys may have been created or enlarged during ice ages but now are ice-free and occupied by streams or rivers. In desert areas, valleys may be entirely dry or carry a watercourse only rarely. In areas of limestone bedrock, dry valleys may also result from drainage now taking place underground rather than at the surface. Rift valleys arise principally from earth movements, rather than erosion. Many different types of valleys are described by geographers, using terms that may be global in use or else applied only locally. ",
      "licenceUrl": "https://commons.wikimedia.org/wiki/File:An_Alpine_Landscape_NZ.jpg"
    },
    <String, dynamic> {
      "image": "1024px-Alpine_landscape,_by_Johan_Christian_Clausen_Dahl,_1821,_oil_on_canvas_-_Germanisches_Nationalmuseum_-_Nuremberg,_Germany_-_DSC03468.jpg",
      "title": "Oil on canvas",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the Oil on canvas image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. \n\n A valley is an elongated low area often running between hills or mountains, which will typically contain a river or stream running from one end to the other. Most valleys are formed by erosion of the land surface by rivers or streams over a very long period. Some valleys are formed through erosion by glacial ice. These glaciers may remain present in valleys in high mountains or polar areas. \n\n At lower latitudes and altitudes, these glacially formed valleys may have been created or enlarged during ice ages but now are ice-free and occupied by streams or rivers. In desert areas, valleys may be entirely dry or carry a watercourse only rarely. In areas of limestone bedrock, dry valleys may also result from drainage now taking place underground rather than at the surface. Rift valleys arise principally from earth movements, rather than erosion. Many different types of valleys are described by geographers, using terms that may be global in use or else applied only locally. ",
      "licenceUrl": "https://commons.wikimedia.org/wiki/File:Alpine_landscape,_by_Johan_Christian_Clausen_Dahl,_1821,_oil_on_canvas_-_Germanisches_Nationalmuseum_-_Nuremberg,_Germany_-_DSC03468.jpg"
    },
    <String, dynamic> {
      "image": "Alpine_Nation_(264131389).jpeg",
      "title": "Alpine Nation",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the Alpine Nation image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. \n\n A valley is an elongated low area often running between hills or mountains, which will typically contain a river or stream running from one end to the other. Most valleys are formed by erosion of the land surface by rivers or streams over a very long period. Some valleys are formed through erosion by glacial ice. These glaciers may remain present in valleys in high mountains or polar areas. \n\n At lower latitudes and altitudes, these glacially formed valleys may have been created or enlarged during ice ages but now are ice-free and occupied by streams or rivers. In desert areas, valleys may be entirely dry or carry a watercourse only rarely. In areas of limestone bedrock, dry valleys may also result from drainage now taking place underground rather than at the surface. Rift valleys arise principally from earth movements, rather than erosion. Many different types of valleys are described by geographers, using terms that may be global in use or else applied only locally. ",
      "licenceUrl": "https://commons.wikimedia.org/wiki/File:Alpine_Nation_(264131389).jpeg"
    },
    <String, dynamic> {
      "image": "1024px-Alpine_valley_(Unsplash).jpg",
      "title": "Alpine valley",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the Alpine valley image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. \n\n A valley is an elongated low area often running between hills or mountains, which will typically contain a river or stream running from one end to the other. Most valleys are formed by erosion of the land surface by rivers or streams over a very long period. Some valleys are formed through erosion by glacial ice. These glaciers may remain present in valleys in high mountains or polar areas. \n\n At lower latitudes and altitudes, these glacially formed valleys may have been created or enlarged during ice ages but now are ice-free and occupied by streams or rivers. In desert areas, valleys may be entirely dry or carry a watercourse only rarely. In areas of limestone bedrock, dry valleys may also result from drainage now taking place underground rather than at the surface. Rift valleys arise principally from earth movements, rather than erosion. Many different types of valleys are described by geographers, using terms that may be global in use or else applied only locally. ",
      "licenceUrl": "https://commons.wikimedia.org/wiki/File:Alpine_valley_(Unsplash).jpg"
    },
    <String, dynamic> {
      "image": "Wyoming_landscape._(43177168225).jpg",
      "title": "Wyoming landscape",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the Wyoming landscape image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. \n\n A valley is an elongated low area often running between hills or mountains, which will typically contain a river or stream running from one end to the other. Most valleys are formed by erosion of the land surface by rivers or streams over a very long period. Some valleys are formed through erosion by glacial ice. These glaciers may remain present in valleys in high mountains or polar areas. \n\n At lower latitudes and altitudes, these glacially formed valleys may have been created or enlarged during ice ages but now are ice-free and occupied by streams or rivers. In desert areas, valleys may be entirely dry or carry a watercourse only rarely. In areas of limestone bedrock, dry valleys may also result from drainage now taking place underground rather than at the surface. Rift valleys arise principally from earth movements, rather than erosion. Many different types of valleys are described by geographers, using terms that may be global in use or else applied only locally. ",
      "licenceUrl": "https://commons.wikimedia.org/wiki/File:Wyoming_landscape._(43177168225).jpg"
    },
    <String, dynamic> {
      "image": "DevHelper_Logo.jpg",
      "title": "App icon",
      "text": "I would like to thank you for taking a look at my example program and I would like to point out that for the App icon image the person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. By tapping on the button you can verify this statement. ",
      "licenceUrl": "https://commons.m.wikimedia.org/wiki/File:DevHelper_Logo.jpg"
    },

  ];

}